variable "gce_project" {}
variable "gce_region" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "env" {}
variable "dbusername" {}
variable "dbpassword" {}
variable "dbhost" {}
variable "dbsize" {}
variable "db_disk_size" {}
variable "dbversion" {}
variable "kubernetes_username" {}
variable "kubernetes_password" {}
variable "node_image" {}
variable "topic" {}
variable "subscription" {}
variable "node_machine_type" {}
variable "node_disk_size_gb" {}
variable "min_node_count" {}
variable "max_node_count" {}
variable "initial_node_eachzone" {}